from enum import Enum

class Tag(Enum):
    # Art
    ART = "Art"
    ALTERED_ART = "Altered Art"
    PIXEL_ART = "Pixel Art"
    POP_OUT_ART = "Pop-Out Art"
    SKETCH_ART = "Sketch Art"
    CUSTOM_ART = "Custom Art"
    AI_ART = "AI Art"
    ARTIST_ART = "Artist Art"
    SWITCHED_ART = "Switched Art"
    UPSCALED_SCAN = "Upscaled Scan"

    # Frame
    FRAME = "Frame"
    BORDERLESS = "Borderless"
    POST_2023_BORDERLESS = "Post-2023 Borderless"
    CUSTOM_MADE_FRAME = "Custom-Made Frame"
    MINIMALIST = "Minimalist"
    STONECUTTER = "Stonecutter"
    EXTENDED_ART = "Extended-Art"
    FNM_PROMO = "FNM Promo"
    FOIL_ETCHED = "Foil-Etched"
    FULL_TEXT = "Full Text"
    FUTURESHIFTED = "Futureshifted"
    M15 = "M15"
    MODERN = "Modern"
    PLANESHIFTED = "Planeshifted"
    RETRO = "Retro"

    # Showcase examples
    SHOWCASE = "Showcase"
    AMONKHET_INVOCATIONS = "Amonkhet Invocations"
    CAPENNA_ART_DECO = "Capenna Art Deco"
    CAPENNA_GOLDEN_AGE = "Capenna Golden Age"
    CAPENNA_SKYSCRAPER = "Capenna Skyscraper"
    CLASSICSHIFTED = "ClassicShifted"
    COMMANDER_LEGENDS = "Commander Legends"
    DND_MODULE = "D&D Module"
    DND_SOURCEBOOK = "D&D Sourcebook"
    DOCTOR_WHO_TARDIS = "Doctor Who TARDIS"
    DOMINARIA_STAINED_GLASS = "Dominaria Stained Glass"
    ELDRAINE_ENCHANTING_TALES = "Eldraine Enchanting Tales"
    ELDRAINE_STORYBOOK = "Eldraine Storybook"
    ENGLISH_MYSTICAL_ARCHIVE = "English Mystical Archive"
    FCA_SHOWCASE = "FCA Showcase"
    IKORIA_CRYSTAL = "Ikoria Crystal"
    INNISTRAD_EQUINOX = "Innistrad Equinox"
    INNISTRAD_FANG = "Innistrad Fang"
    IXALAN_COIN = "Ixalan Coin"
    JAPANESE_MYSTICAL_ARCHIVE = "Japanese Mystical Archive"
    JAPAN_SHOWCASE = "Japan Showcase"
    KALADESH_INVENTIONS = "Kaladesh Inventions"
    KALDHEIM_VIKING = "Kaldheim Viking"
    KAMIGAWA_NEON = "Kamigawa Neon"
    KAMIGAWA_NINJA = "Kamigawa Ninja"
    KAMIGAWA_SAMURAI = "Kamigawa Samurai"
    LOTR_RING = "LOTR Ring"
    LOTR_SCROLLS_OF_MIDDLE_EARTH = "LOTR Scrolls of Middle-earth"
    M21_SPELLBOOK = "M21 Spellbook"
    PHYREXIA_OIL = "Phyrexia Oil"
    RAVNICA_ARCHITECTURE = "Ravnica Architecture"
    SKETCH_FRAME = "Sketch Frame"
    TARKIR_DRAGON_WING = "Tarkir Dragon Wing"
    THEROS_NYX = "Theros Nyx"
    ZENDIKAR_EXPEDITIONS = "Zendikar Expeditions"
    ZENDIKAR_HEDRON = "Zendikar Hedron"
    ZENDIKAR_RISING_EXPEDITIONS = "Zendikar Rising Expeditions"

    # Full-Art
    FULL_ART = "Full-Art"

    # Misc
    MISC = "Misc"
    ALTERNATE_NAME = "Alternate Name"
    NICKNAME = "Nickname"
    CARD = "Card"
    ETERNAL_NIGHT_CARD = "Eternal Night Card"
    REALISTIC = "Realistic"
    SECRET_LAIR = "Secret Lair"
    TEXTLESS = "Textless"
    NON_BLACK_BORDER = "Non-Black Border"
    GOLD_BORDER = "Gold Border"
    SILVER_BORDER = "Silver Border"
    WHITE_BORDER = "White Border"

    # NSFW
    NSFW = "NSFW"

    # Universe
    UNIVERSE = "Universe"
    ANIME = "Anime"
    HATSUNE_MIKU = "Hatsune Miku"
    AVATAR_THE_LAST_AIRBENDER = "Avatar The Last Airbender"
    DR_WHO = "Dr Who"
    FALLOUT = "Fallout"
    FINAL_FANTASY = "Final Fantasy"
    IN_MULTIVERSE = "In-Multiverse"
    LEAGUE_OF_LEGENDS = "League of Legends"
    LORD_OF_THE_RINGS = "Lord of the Rings"
    SPIDER_MAN = "Spider-Man"
    WARHAMMER_40K = "Warhammer 40k"
